<?php

namespace app\controllers;

use function foo\func;
use PhpAmqpLib\Connection\AMQPConnection;
use PhpAmqpLib\Message\AMQPMessage;
use Yii;
use yii\db\Exception;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;

class RabbitmqController extends Controller
{
    private $client = null;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
//        $this->client = new AMQPConnection();
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        echo 'Welcome to RabbitMQ';
    }

    // 生产者
    public function actionCreate()
    {
        $config = \Yii::$app->params['rabbitmq'];
        $this->client = new AMQPConnection($config['host'], $config['port'], $config['user'], $config['password']);
//        $this->client = new \AMQPConnection($config);

        // 建立一个连接通道，声明一个可以发送消息的队列hello
        $channel = $this->client->channel();

        $queueName = 'hello' . rand(0,9);
        $channel->queue_declare($queueName);

        // 定义一个消息，消息内容为Hello World!
        $msg = new AMQPMessage('hello world !');
        $channel->basic_publish($msg, '', $queueName);

        var_export($channel);die;
    }

}
